public class Address {
    public void homeAddress(){
        String yourName = 'Sumeyra';
      system.debug('My name is ' + yourName);
      Integer numberFamilyNumbers = 3;
      system.debug('Total number of my family members: ' + numberFamilyNumbers);
      String houseName= 'DreamHouse';
      system.debug('my house name is ' + houseName);
      String houseNumber = '54';
      system.debug('The house number is ' + houseNumber);
      String streetName = 'Icy Storm Avenue ';
      system.debug('my street name is ' + streetName);
      String cityName = ' Columbus';
      system.debug('My city is' + cityName);
      String stateName = 'New Jersey';
     system.debug('My state is ' + stateName);
     String stateIsoCode = 'NJ';
     system.debug('The state ISO code is: ' + stateisoCode);
     String countryname= 'United States';
     system.debug('My country name is; ' + countryName);
     String countryIsoCode = 'US';
     system.debug('The Country\'s ISO code is: ' +countryIsoCode);
     String zipCode = '07026';
     system.debug('The Zip Code is:' + zipCode);
     Boolean isCurrentHome = false;
     System.debug('Is this your current home? ' + isCurrenthome);
   }

}

