@isTest
public class CalculatorTest {
    @isTest
    public static void textMessages(){
        Calculator.welcomeMessage();
        calculator.printNewMessage('this is a test');
            }
            @isTest
            private static void addTest1(){
                integer calcAdd = calculator.add(10,11,20);
                system.assertEquals(45,calcAdd);
            }
            @isTest
            private static void addTest1(){
                integer calcAdd = calculator.add(10,11,20);
                system.assertEquals(45,calcAdd);

        }
  